# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
#  - name: Posts
#    url: '#posts'
#    weight: 20
  - name: Projects
    url: '#myproject'
    weight: 20
  - name: Publications
    url: '#mypublication'
    weight: 30
  - name: Awards
    url: '#award'
    weight: 40
  - name: Conferences and Workshops
    url: '#conference'
    weight: 50
  - name: Teaching
    url: '#teaching'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: Resume
#    url: uploads/resume.pdf
#    weight: 70
